### ISSUE TITLE
Why has this repo the branch "main" as default instead of "master"?

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-manage-service#25]

**Comment by ostcar** [comment]
Because "main" is the new default on github. See https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

Maybe we should rename the default branches of all old repos to the new official default. Please open a issue in the OpenSlides repo if you want to do this.

**Comment by GabrielInTheWorld** [comment]
> Because "main" is the new default on github. See https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/
> 
> Maybe we should rename the default branches of all old repos to the new official default. Please open a issue in the OpenSlides repo if you want to do this.

No, I think, it is a better way to only rename the default branch for this repo.

**Comment by normanjaeckel** [comment]
Renaming the default branches of the other repositories is an open issue which should be done when we move from OpenSlides3 to 4. https://github.com/OpenSlides/OpenSlides/issues/5829

**Comment by ostcar** [comment]
So there is nothing to do here. All other discussion can be done in the issue that @normanjaeckel linked above.
