### ISSUE TITLE
Customize docker-compose.yml

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-manage-service#45]
@gsiv As discussed:

Please fill this issue with your favorites that should be customizable in the docker-compose.yml and/or the docker-stack.yml. 

The current proposal is that we add a flag like `--profile=swarm` (default would be `--profile=compose`) to produce a docker-stack.yml instead of a docker-compose.yml. What are the differences between these two files?

What customizations do you need else (which should not be solved by a fork of this repo). Such customitzations could be provided by a config file with al `--config` flag as discussed.

**Comment by gsiv** [comment]
To add some context to this issue, the purpose of `openslides-manage-service` is to simplify the setup of OpenSlides instances for individuals intending to self-host OpenSlides.  This discussion is about the management tool's suitability for managing a very large number of instances.

`openslides-manage-service` manages one instance at a time.  For managing multiple instances, a wrapper tool is going to iterate over the individual instances and call this new management tool for each one.  `osinstancectl` basically already does just this; it just needs to be updated to additionally call the management tool where necessary.  This is all fine by me.

> The current proposal is that we add a flag like --profile=swarm (default would be --profile=compose) to produce a docker-stack.yml instead of a docker-compose.yml. What are the differences between these two files?

The differences between Compose and Stack YAML files are rather small.  You can see the actual differences in regards to OpenSlides by comparing https://github.com/OpenSlides/OpenSlides/blob/master/docker/docker-compose.yml.m4 and https://github.com/OpenSlides/OpenSlides/blob/master/docker/docker-stack.yml.m4.  You will notice that it mostly comes down to incompatibilities with `depends_on` and `deploy`.

The differences are, in fact, small enough that they could be managed within a single template.  When I introduced the m4 templates, I avoided doing so right away for the sake of simplicity but it would be rather straightforward to merge them.

See also https://github.com/compose-spec/compose-spec/blob/master/deploy.md.

> What customizations do you need else (which should not be solved by a fork of this repo). Such customizations could be provided by a config file with al --config flag as discussed.

Having thought about this a little more, I believe asking which `docker-compose.yml` customizations we want the tool to support is the wrong approach.  Also, accepting that users need to recompile the tool in order to make minor changes to a template is, in my opinion, indicative of something being wrong.  (Yes, I know I was more open to it during our talk. :)

As you are aware, `docker-compose.yml` allows for almost infinite customizations that cannot possibly be covered by the tool or a configuration file format.  As long as you are dealing with one or two instances, you may be content with having to make certain customizations *after* the configuration files have been generated; however, that obviously stops being a viable method very quickly.

Compiling custom versions of the tool is an option; however, it's a silly thing to do just because the template must be baked in.  You may also underestimate just how often customizations to the templates are required.  If we were to compile custom versions of the tool for each – possibly ad hoc – template modification, we would end up with a significant number of management tools in use at the same time.  (Ultimately, we would probably end up with a wrapper around some kind of recompile-on-each-invocation workflow instead. :)

These are examples of `docker-stack.yml.m4` customizations currently in production here:

- `image` for various services (additionally via `.env`)
- `deploy` settings, including `replicas` and placement constraints (additionally via `.env`)
- `command` overrides
- `networks` settings, e.g., regarding encryption
- `sysctls` settings

Additional likely candidates:

- `volumes` settings
- entirely new services

Before making a list of which of these configuration options the tool should support, I would like to propose a `--template` option.  It should be possible to dump the included template, customize it, and then use that copy instead.  For example:

```bash
./manage dump-template --profile=swarm > custom.yml.tpl
./manage setup --template=custom.yml.tpl
```

Given the `--template` option, the requirements for the tool's configuration files (`--config`) become much more manageable.  They would remain unchanged from their role in OpenSlides 3 which is to persist all *instance-specific* configuration.  This includes non-global settings such as image versions, the domain and port, and scaling settings.  See https://github.com/OpenSlides/OpenSlides/blob/master/docker/.env for a complete list of options.

I don't know where the file for `--config` would come from yet.  Would the management tool write it when creating the instance?  Would it be based on another template like `.env`?  In that case the same considerations would probably apply to this template as well, i.e., it should be customizable with an option like `--config-template`.

Obviously, you could and should still hard-code decent defaults and continue to hide the templates from casual users.

**Comment by ostcar** [comment]
@gsiv This sounds like a good idea and should be easy to do.

**Comment by normanjaeckel** [comment]
Should be done with #74
