### ISSUE TITLE
Enable HTTPS support

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-manage-service#46]
@ostcar Please help and lets discuss this.

**Comment by refda** [comment]
It's also possible to enable https with apache. This is also useful when using a management system like KeyHelp or Plesk.
Check if activated:
```
sudo a2enmod ssl
sudo a2enmod proxy
sudo a2enmod proxy_balancer
sudo a2enmod proxy_http
```
Apache directives:
```
<IfModule mod_proxy.c>
        ProxyPass /.well-known/acme-challenge !
</IfModule>

Alias /.well-known/acme-challenge /home/keyhelp/www/.well-known/acme-challenge

ProxyPass / http://127.0.0.1:8000/
ProxyPassReverse / http://127.0.0.1:8000/
```
In this case the let's encrypt verification path is not proxied.

**Comment by peb-adr** [comment]
Okay this is honestly a pretty easy fix.
What I had to do to have local https:
  1. `cd _myinstancefolder_`
  2. `cp _openslidesrepo_/proxy/make-localhost-cert.sh .`
  3. `mkdir certs`
  4. `./make-localhost-cert.sh`
  5. edit docker-compose.yml:
    - add `ENABLE_LOCAL_HTTPS: 1` to the default environment
    - add `volumes: - ./certs/:/certs` to the proxy service
  6. `docker-compose up -d`
magic!

So I would propose to have the manage service do these steps.
I think in the config.yml one should be able to set an option like `.enableLocalHTTPS` similar to `.disablePostgres`
If set, the compose file will be generated with the additions described above in 5.
I'm just a bit unsure about how the certs could be generated, as the `make-localhost-cert.sh` script is in the main repo and setting up OS4 should not require to clone the repo.
However the script is basically only doing `mkdir certs && openssl ...` so maybe these two system calls should just be done directly from the manage-tool.
Or perhaps there are even go library functions to call to generate such a cert.

But yeah, so long the local certs find their way into the /certs folder within the proxy container, using them is just a matter of setting `ENABLE_LOCAL_HTTPS=1` since the new proxy.

**Comment by peb-adr** [comment]
> When enabled, the proxy would automatically generate self-signed certificates. We even went through the mkcert vs. OpenSSL discussion already (and chose OpenSSL).

@gsiv This is not the proxy generating the certs it automatically, rather the dev-Makefile runs openssl and the Dockerfile.dev includes the cert files into the proxy image.

So rethinking my proposal from above a bit.
As the manage-tool is responsible for generating the compose file, it should use a config option `enableLocalHTTPS`.
Providing the cert and key might be better as a secret rather than a volume, like @ostcar proposed.
In that case I would extend the proxy to respect env vars like `HTTPS_CERT_FILE` and `HTTPS_KEY_FILE` which can then be set to `/run/secrets/cert.crt` and `/run/secrets/cert.key`. (currently its hard coded to look for `/certs/cert.crt` and `/certs/cert.key`)

I feel like thats a good way to handle it and would be in line with the other `*_FILE` env vars added lately pointing towards secrets

**Comment by peb-adr** [comment]
Worked on in #103

**Comment by normanjaeckel** [comment]
Done by #103
