### ISSUE TITLE
Send migration index to datastore when initial data are created

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-manage-service#58]
How can I send the migration index to the datastore during the creation of initial data?

As you see [here](https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/initialdata/initialdata.go#L160), I fire a bunch of Create events.

See also [here](https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/initialdata/initialdata.go#L151).

**Comment by FinnStutzenstein** [comment]
You do not have to. With https://github.com/OpenSlides/openslides-datastore-service/pull/145 I fixed a little mistake. This is the workflow now:

- The manage service sends a single write request[1] to the empty datastore to fill it with initial data. It has a default migration index of -1, so this position will get MI -1.
- The migrate-tool must run before the backend starts.[2] If it detects a -1, it will set the datastore's MI to the current MI and quits without doing any migrations. This can only be done by the backend since it is the single service knowing about actual migrations.

The second step currently enforces you to always include up-to-date initial-data with respect to the scheme. If you want to have a different migration index than "current" (-> -1), we have to include an option to set the MI. E.g. adding it as a param to the write request, which is only valid if the DS is empty, so it can just be used on the first write request.

This is more of a "how will the initial data be used". I can imagine that Emanuel maybe wants different initial data for different clients (or not? IDK), so in this case an up-to-data initial data makes sense.

[1] The single write request is essential, if you are just doing create events: within one position the datastore must be consistent, so if you split the initial into multiple write requests, the resulting positions itself may be not consistent. This will break the migrations.

[2] This is the part that will be needed to be done very differently in the productive setup than the development one. Since in the dev setup the backend is started as a singleton-service, I just added it to the entrypoint which works fine there: https://github.com/OpenSlides/openslides-backend/blob/master/dev/entrypoint.sh#L14

**Comment by normanjaeckel** [comment]
Ok, so for the moment I just always use an up-to-date initial-data file with migration_index -1 and I do not send any index so the datastore uses the default. We can change this later if @emanuelschuetze prefers the second way.

**Comment by normanjaeckel** [comment]
Ah the last comment was not up to date, right?

**Comment by FinnStutzenstein** [comment]
Right, I'll add a way to send an initial MI to the Datastore.

**Comment by FinnStutzenstein** [comment]
See https://github.com/OpenSlides/openslides-datastore-service/pull/147 and https://github.com/OpenSlides/OpenSlides/wiki/Datastore-Service#interface. I've added `migration_index` to the payload of `write`. It is only allowed when the DS is empty, so it is allowed on the first (successful) write request.

**Comment by FinnStutzenstein** [comment]
SO with this PR you can fix the MI of the initial data (as in https://github.com/OpenSlides/OpenSlides/pull/6205) and the initial data itself.
