### ISSUE TITLE
initial-data: Wait for datastore service to become available

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#87]
In order for `openslides initial-data` to succeed, the database must be set up, and the datastore service must be ready to accept and process requests.

Currently, the `initial-data` command fails if the stack is not ready.  While this makes sense generally, there appears to be no consistent workflow for running the command at the correct time.

The README's instructions suggest to run the following commands right after another:

```bash
docker-compose up --detach
./openslides initial-data
```

Whether this works depends on how quickly the relevant containers start on a given system.  Since `docker-compose` or `docker stack deploy` exit immediately while the containers are still starting up, `openslides initial-data` may be executed too early and fail.  Users are essentially left repeatedly trying the command in a loop until it succeeds.

I would like to propose a change to or a new option for `initial-data` that would cause it to wait for the relevant OpenSlides services to be become available first.

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/OpenSlides/issues/6257

**Comment by peb-adr** [comment]
I think this should be implemented more generically in the connection-dailing module.
So that other commands that connect to the server part can benefit from this too.

Also it would be nice to have different exit codes indicating if there was a connect issue or a problem during the actual execution of the command, for example:

`openslides create-user`
  - connect error -> exit 1
  - backend_response.body.success == false -> exit 2 or alternatively
  backend_response.code != 200 -> exit 2

maybe @gsiv has some ideas too, what would be appropriate.

**Comment by normanjaeckel** [comment]
Is this still valid? After we run the initial-data command via the backend and (so I think) the backend ensures a running datastore, I think we can close this.

**Comment by normanjaeckel** [comment]
I think this is invalid. Please reopen if there are any problems left.
